-- 用户表
CREATE TABLE "USER" (
    "ID" NUMBER(10) NOT NULL,
    "name" VARCHAR2(50 BYTE) NULL ,
    "AGE" NUMBER(10) NULL ,
    "AVATAR" VARCHAR2(50 BYTE) NULL
);

-- 地址表
CREATE TABLE "ADDRESS" (
    "ID" NUMBER(10) NOT NULL,
    "USER_ID" NUMBER(10) NOT NULL,
    "ADDR" VARCHAR2(50 BYTE) NULL ,
    "TEL" VARCHAR2(50 BYTE) NULL
);
